# version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    restart: always
    networks:
      - inception_net

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - '443:443'
    restart: always
    depends_on:
      - wordpress
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - wp_data:/var/www/html
      - ssl_certs:/etc/nginx/ssl
    networks:
      - inception_net
  
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception_net

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      device: ${HOME}/data/db_data
      o: bind
      type: none

  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      device: ${HOME}/data/wp_data
      o: bind
      type: none

  ssl_certs:
    name: ssl_certs
    driver: local
    driver_opts:
      device: ${HOME}/data/ssl_certs
      o: bind
      type: none

networks:
  inception_net:
    driver: bridge
